<template>
  <article>
<!--  -->
    <div v-if="doneLoading" class="wrapper">
      <img :src="imageUrl" :alt="post.image.alternativeText">
      <span>
        {{ dateString }}
      </span>
      <h1 class="subtitle">
        {{ post.title }}
      </h1>
      <div v-html="post.html" class="vhtmlContainer" />
      <social-share-buttons
        :options="socialShareOptions"
      />
    </div>
<!--  -->
    <loading-indicator
      v-else-if="!error && loading"
    />

    <error-indicator
      v-else-if="error"
    />

  </article>
</template>

<script>
import LoadingIndicator from '@/components/LoadingIndicator.vue'
import ErrorIndicator from '@/components/ErrorIndicator.vue'
import SocialShareButtons from '@/components/SocialShareButtons.vue'

export default {
  name: 'BlogPost',
  props: {
    post: {
      type: Object,
      default: () => ({ id: 0, date: '', title: '', slug: '', image: {}, html: '', introText: '', fullText: '', updated_at: '' }),
      required: true
    },
    apiBaseUrl: {
      type: String,
      default: () => ('https://staff.waxshop.ca'),
      required: true
    },
    // html: {
    //   type: String,
    //   default: () => (''),
    //   required: true
    // },
    loading: {
      type: Boolean,
      default: () => false,
      require: true
    },
    error: {
      type: null || Object,
      default: () => false,
      require: true
    }
  },
  components: {
    LoadingIndicator,
    ErrorIndicator,
    SocialShareButtons
  },
  data() {
    return {
      months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    }
  },
  computed: {
    imageUrl() {
      return this.doneLoading && this.post.image && this.post.image.hasOwnProperty('formats')
        ? this.apiBaseUrl + this.post.image.formats.large.url
        : ''
    },
    dateString() {
      if (!this.post || !this.post.date) { return }
      const [ yearString, monthString, dayString ] = this.post.date.split('-')
      const monthIndex = Number(monthString) - 1
      return `${this.months[monthIndex || 0]} ${dayString}, ${yearString}`
    },
    doneLoading() {
      return !this.loading && !this.error && this.post && this.post.id && this.post.id > 0
    },
    socialShareOptions() {
      return {
        services: ['facebook', 'twitter', 'email'],
        url: process.env.BASE_URL + this.$route.fullPath,
        title: this.post.title,
        text: this.post.introText,
        image: this.imageUrl,
        label: 'post',
        name: 'The Wax Shop Kelowna'
      }
    }
  }

}
</script>

<style lang="scss" scoped>
@import '@/scss/shared/blog-post-shared.scss';
article {
  div.wrapper.loading {
    padding-top: 96px;
    padding-bottom: 96px;
  }
}
</style>

<style lang="scss">
// unscoped so it applies to content dynamically generated by v-html
div.vhtmlContainer {
  span.italic {
    font-style: italic;
  }
  span.bold {
    font-weight: bold;
  }
  span.strikethrough {
    text-decoration: line-through;
  }
  span.underline {
    text-decoration: underline;
  }
  margin-bottom: 32px;
  p, h2 {
    padding: 16px 2px;
    padding-top: 0;
  }
  h2 {
    font-weight: bold;
    font-size: 1.3rem;
    padding-bottom: 6px;
  }
}
</style>
